name: Preview Changes
on:
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::091512051921:role/GitHubActionsRole
          aws-region: ap-northeast-1

      - uses: hashicorp/setup-terraform@v3
      - id: plan
        run: |
          cd ./terraform
          terraform init
          {
            echo "plan<<EOF"
            terraform plan
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - uses: kayac/ecspresso@v2
        with:
          version: v2.6.4
      - id: ecspresso-diff-ui
        run: |
          cd ./ui
          {
            echo "diff<<EOF"
            ecspresso diff
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - id: ecspresso-diff-omikuji
        run: |
          cd ./omikuji
          {
            echo "diff<<EOF"
            ecspresso diff
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: List buckets
        id: buckets
        run: |
          {
            echo "buckets<<EOF"
            aws s3 ls
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - name: Comment on a PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat > /tmp/comment.md << 'EOF'
          ## S3 Buckets

          ```
          ${{ steps.buckets.outputs.buckets }}
          ```

          ## Terraform plan

          ```
          ${{ steps.plan.outputs.plan }}
          ```

          ## ui / ecspresso diff

          ```
          ${{ steps.ecspresso-diff-ui.outputs.diff }}
          ```

          ## omikuji / ecspresso diff

          ```
          ${{ steps.ecspresso-diff-omikuji.outputs.diff }}
          ```
          EOF
          )"
          gh pr comment ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --body /tmp/comment.md
