name: Preview Changes
on:
  pull_request:
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
permissions:
  id-token: write
  contents: read
  pull-requests: write
jobs:
  preview:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
      - uses: aws-actions/configure-aws-credentials@61815dcd50bd041e203e49132bacad1fd04d2708 # v5.1.1
        with:
          role-to-assume: arn:aws:iam::091512051921:role/GitHubActionsRole
          aws-region: ap-northeast-1

      - uses: hashicorp/setup-terraform@b9cd54a3c349d3f38e8881555d616ced269862dd # v3.1.2
      - id: plan
        run: |
          cd ./terraform
          terraform init
          {
            echo "plan<<EOF"
            terraform plan -no-color
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - uses: kayac/ecspresso@2c38c148ea49af35672cb0e8420d443006dd4a40 # v2.6.4
        with:
          version: v2.6.4
      - id: ecspresso-diff-ui
        run: |
          cd ./ui
          {
            echo "diff<<EOF"
            ecspresso diff --no-color
            echo "EOF"
          } >> $GITHUB_OUTPUT
      - id: ecspresso-diff-omikuji
        run: |
          cd ./omikuji
          {
            echo "diff<<EOF"
            ecspresso diff --no-color
            echo "EOF"
          } >> $GITHUB_OUTPUT

      - name: Comment on a PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cat > /tmp/comment.md << 'EOF'
          ## Terraform plan

          ```
          ${{ steps.plan.outputs.plan }}
          ```

          ## ui / ecspresso diff

          ```
          ${{ steps.ecspresso-diff-ui.outputs.diff }}
          ```

          ## omikuji / ecspresso diff

          ```
          ${{ steps.ecspresso-diff-omikuji.outputs.diff }}
          ```
          EOF

          gh pr comment ${{ github.event.pull_request.number }} \
            --repo ${{ github.repository }} \
            --body-file /tmp/comment.md
